In [2]:
import cv2
import numpy as np

In [2]:
# Get camera 
cam = cv2.VideoCapture(0)

cv2.namedWindow("test")

img_counter = 0

while True:
    ret, frame = cam.read()
    if not ret:
        print("failed to grab frame")
        break
    cv2.imshow("test", frame)
    print(np.array(frame))
    k = cv2.waitKey(1)
    if k%256 == 27:
        # ESC pressed
        print("Escape hit, closing...")
        break
    elif k%256 == 32:
        # SPACE pressed
        img_name = "opencv_frame_{}.png".format(img_counter)
        cv2.imwrite(img_name, frame)
        print("{} written!".format(img_name))
        img_counter += 1

cam.release()

cv2.destroyAllWindows()

[[[ 92  87  60]
  [ 94  90  63]
  [ 94  90  63]
  ...
  [141 132  97]
  [141 132  97]
  [140 131  96]]

 [[ 81  75  49]
  [ 86  80  54]
  [ 88  82  56]
  ...
  [141 132  97]
  [140 131  96]
  [140 131  96]]

 [[ 60  51  27]
  [ 70  62  37]
  [ 72  65  38]
  ...
  [141 133  96]
  [140 131  96]
  [140 131  96]]

 ...

 [[ 88  82  53]
  [ 87  81  52]
  [ 87  81  52]
  ...
  [255 254 254]
  [255 254 254]
  [255 254 254]]

 [[ 87  81  52]
  [ 87  81  52]
  [ 87  81  52]
  ...
  [255 254 254]
  [255 254 254]
  [255 254 254]]

 [[ 87  81  52]
  [ 87  81  52]
  [ 87  81  52]
  ...
  [255 254 254]
  [255 254 254]
  [255 254 254]]]
[[[105  97  68]
  [107  99  70]
  [107 100  72]
  ...
  [155 144 107]
  [154 143 106]
  [154 143 106]]

 [[ 98  88  60]
  [101  92  64]
  [102  94  66]
  ...
  [154 143 106]
  [154 143 106]
  [153 142 105]]

 [[ 74  63  36]
  [ 81  70  43]
  [ 85  74  47]
  ...
  [154 143 106]
  [154 143 106]
  [153 142 105]]

 ...

 [[ 96  87  59]
  [ 96  87  59]
  [ 96  87  59]
  ..

[[[ 73  57  34]
  [ 74  58  35]
  [ 75  60  35]
  ...
  [174 171 133]
  [174 171 133]
  [173 170 132]]

 [[ 64  50  28]
  [ 66  51  29]
  [ 65  51  28]
  ...
  [174 171 133]
  [173 170 132]
  [173 170 132]]

 [[ 64  50  31]
  [ 63  50  31]
  [ 62  49  29]
  ...
  [174 171 133]
  [173 170 132]
  [173 170 132]]

 ...

 [[136 133  95]
  [136 133  94]
  [136 133  94]
  ...
  [ 75  56  34]
  [ 77  57  35]
  [ 78  57  35]]

 [[136 133  94]
  [136 133  94]
  [136 133  94]
  ...
  [ 75  56  34]
  [ 76  56  34]
  [ 76  56  34]]

 [[135 132  93]
  [136 133  94]
  [136 133  95]
  ...
  [ 74  55  33]
  [ 75  55  33]
  [ 75  55  33]]]
[[[ 57  42  19]
  [ 61  45  22]
  [ 64  46  24]
  ...
  [176 172 134]
  [174 171 133]
  [174 171 133]]

 [[ 62  48  25]
  [ 64  49  26]
  [ 66  50  28]
  ...
  [174 171 133]
  [174 171 133]
  [173 170 132]]

 [[ 61  49  27]
  [ 63  50  28]
  [ 64  50  28]
  ...
  [174 171 133]
  [173 170 132]
  [173 170 132]]

 ...

 [[135 132  92]
  [135 132  92]
  [136 134  93]
  ..

[[[ 63  45  23]
  [ 64  46  23]
  [ 65  48  23]
  ...
  [180 172 132]
  [178 171 131]
  [178 171 131]]

 [[ 63  46  24]
  [ 63  46  24]
  [ 64  48  24]
  ...
  [178 171 131]
  [178 171 131]
  [177 170 130]]

 [[ 63  48  27]
  [ 63  48  27]
  [ 63  49  27]
  ...
  [178 171 131]
  [177 170 130]
  [177 170 130]]

 ...

 [[139 132  90]
  [139 132  90]
  [139 132  90]
  ...
  [ 74  55  30]
  [ 74  55  29]
  [ 74  55  29]]

 [[139 132  90]
  [139 132  90]
  [139 132  90]
  ...
  [ 75  56  31]
  [ 75  56  31]
  [ 76  57  32]]

 [[139 132  90]
  [139 132  90]
  [139 132  90]
  ...
  [ 76  57  33]
  [ 77  58  34]
  [ 79  59  35]]]
[[[ 63  45  23]
  [ 63  45  22]
  [ 65  48  23]
  ...
  [180 172 132]
  [178 171 131]
  [177 170 130]]

 [[ 63  46  24]
  [ 62  45  23]
  [ 63  47  23]
  ...
  [178 171 131]
  [178 171 131]
  [177 170 130]]

 [[ 62  47  26]
  [ 63  48  27]
  [ 63  49  27]
  ...
  [178 171 131]
  [177 170 130]
  [177 170 130]]

 ...

 [[139 132  92]
  [139 132  92]
  [140 133  93]
  ..

[[[ 65  47  25]
  [ 67  48  26]
  [ 68  48  26]
  ...
  [180 172 130]
  [179 170 129]
  [179 170 129]]

 [[ 62  45  23]
  [ 63  46  24]
  [ 66  48  27]
  ...
  [180 172 130]
  [179 170 129]
  [179 170 129]]

 [[ 61  45  26]
  [ 61  45  26]
  [ 61  45  26]
  ...
  [180 172 130]
  [179 170 129]
  [178 169 127]]

 ...

 [[144 138  96]
  [145 138  96]
  [146 138  96]
  ...
  [ 75  55  33]
  [ 76  56  34]
  [ 79  58  37]]

 [[145 138  96]
  [145 138  96]
  [144 137  95]
  ...
  [ 75  55  33]
  [ 76  56  34]
  [ 77  57  35]]

 [[144 137  95]
  [144 137  95]
  [143 137  95]
  ...
  [ 75  55  33]
  [ 76  56  34]
  [ 76  56  34]]]
[[[ 58  41  16]
  [ 61  43  18]
  [ 66  47  22]
  ...
  [182 173 131]
  [182 173 131]
  [180 172 130]]

 [[ 61  44  21]
  [ 60  43  20]
  [ 65  46  23]
  ...
  [182 173 131]
  [180 172 130]
  [180 172 130]]

 [[ 61  46  26]
  [ 60  44  25]
  [ 61  44  25]
  ...
  [180 172 130]
  [180 172 130]
  [179 170 129]]

 ...

 [[144 136  96]
  [145 138  97]
  [145 138  97]
  ..

[[[ 65  42  20]
  [ 65  42  20]
  [ 66  44  20]
  ...
  [180 172 130]
  [179 170 129]
  [179 170 129]]

 [[ 65  44  23]
  [ 64  43  22]
  [ 64  43  21]
  ...
  [180 172 130]
  [179 170 129]
  [178 169 127]]

 [[ 62  44  25]
  [ 62  44  25]
  [ 62  44  25]
  ...
  [179 170 129]
  [179 170 129]
  [178 169 127]]

 ...

 [[144 136  94]
  [144 136  94]
  [144 136  94]
  ...
  [ 78  57  35]
  [ 78  56  33]
  [ 78  57  33]]

 [[144 136  94]
  [144 136  94]
  [144 136  94]
  ...
  [ 78  57  35]
  [ 78  56  33]
  [ 78  57  33]]

 [[144 136  94]
  [144 136  94]
  [144 136  94]
  ...
  [ 78  57  35]
  [ 78  56  33]
  [ 80  58  34]]]
[[[ 64  44  27]
  [ 62  42  24]
  [ 61  40  21]
  ...
  [180 172 130]
  [179 170 129]
  [179 170 129]]

 [[ 62  43  26]
  [ 60  41  23]
  [ 61  41  23]
  ...
  [180 172 130]
  [179 170 129]
  [178 169 127]]

 [[ 61  44  28]
  [ 60  43  27]
  [ 61  44  26]
  ...
  [179 170 129]
  [179 170 129]
  [178 169 127]]

 ...

 [[143 134  92]
  [144 136  94]
  [144 136  94]
  ..

[[[ 72  52  29]
  [ 74  53  31]
  [ 77  55  33]
  ...
  [189 179 139]
  [187 178 138]
  [187 178 138]]

 [[ 71  51  30]
  [ 71  51  30]
  [ 73  52  32]
  ...
  [187 178 138]
  [187 178 138]
  [187 178 138]]

 [[ 70  52  33]
  [ 70  52  33]
  [ 70  52  33]
  ...
  [187 178 138]
  [187 178 138]
  [186 177 137]]

 ...

 [[154 146 104]
  [153 145 102]
  [153 146 102]
  ...
  [ 97  75  48]
  [ 96  74  46]
  [ 95  73  44]]

 [[153 147 103]
  [152 146 102]
  [152 146 101]
  ...
  [ 96  75  48]
  [ 95  74  46]
  [ 94  73  44]]

 [[153 147 102]
  [152 146 101]
  [152 146 101]
  ...
  [ 94  74  47]
  [ 94  74  46]
  [ 93  73  44]]]
[[[ 72  51  29]
  [ 73  53  31]
  [ 75  55  33]
  ...
  [189 179 139]
  [187 178 138]
  [187 178 138]]

 [[ 71  51  30]
  [ 71  51  30]
  [ 72  53  31]
  ...
  [187 178 138]
  [187 178 138]
  [187 178 138]]

 [[ 70  53  32]
  [ 69  51  31]
  [ 70  53  32]
  ...
  [187 178 138]
  [187 178 138]
  [186 177 137]]

 ...

 [[152 145 103]
  [150 144 101]
  [152 145 103]
  ..

[[[ 54  34  16]
  [ 52  33  15]
  [ 52  33  14]
  ...
  [162 154 117]
  [161 153 115]
  [161 153 115]]

 [[ 55  36  19]
  [ 54  35  18]
  [ 54  36  17]
  ...
  [162 154 117]
  [161 153 115]
  [160 152 114]]

 [[ 53  36  20]
  [ 53  36  20]
  [ 53  36  20]
  ...
  [161 153 115]
  [161 153 115]
  [160 152 114]]

 ...

 [[123 117  79]
  [123 117  79]
  [123 117  79]
  ...
  [ 69  51  31]
  [ 72  53  34]
  [ 73  55  35]]

 [[123 117  79]
  [123 117  79]
  [123 117  79]
  ...
  [ 70  52  32]
  [ 72  55  35]
  [ 73  56  36]]

 [[123 117  79]
  [123 117  79]
  [123 117  79]
  ...
  [ 69  51  31]
  [ 70  54  33]
  [ 71  55  35]]]
[[[ 53  35  19]
  [ 53  35  19]
  [ 52  35  18]
  ...
  [160 152 114]
  [160 152 114]
  [159 151 113]]

 [[ 52  35  20]
  [ 52  35  19]
  [ 52  35  19]
  ...
  [160 152 114]
  [159 151 113]
  [159 151 113]]

 [[ 50  36  22]
  [ 51  36  22]
  [ 52  36  21]
  ...
  [159 151 113]
  [159 151 113]
  [159 151 113]]

 ...

 [[123 117  79]
  [123 117  79]
  [123 117  79]
  ..

[[[ 80  58  34]
  [ 79  57  32]
  [ 78  57  33]
  ...
  [196 186 146]
  [194 185 145]
  [194 185 145]]

 [[ 79  59  36]
  [ 78  58  34]
  [ 78  57  35]
  ...
  [194 185 145]
  [194 185 145]
  [193 184 144]]

 [[ 74  56  35]
  [ 75  57  36]
  [ 76  57  36]
  ...
  [194 185 145]
  [194 185 145]
  [193 184 144]]

 ...

 [[160 153 111]
  [160 153 111]
  [160 153 111]
  ...
  [ 99  76  48]
  [ 98  75  47]
  [ 94  72  43]]

 [[160 153 111]
  [160 153 111]
  [160 153 111]
  ...
  [100  77  50]
  [ 98  75  47]
  [ 95  73  44]]

 [[160 153 111]
  [160 153 111]
  [160 153 111]
  ...
  [100  77  51]
  [ 98  75  47]
  [ 97  74  46]]]
[[[ 75  56  31]
  [ 77  57  32]
  [ 81  59  35]
  ...
  [198 188 149]
  [197 187 148]
  [197 187 148]]

 [[ 75  57  33]
  [ 77  58  34]
  [ 80  60  37]
  ...
  [198 188 149]
  [197 187 148]
  [197 187 148]]

 [[ 76  59  37]
  [ 76  59  37]
  [ 77  60  38]
  ...
  [197 187 148]
  [197 187 148]
  [196 186 146]]

 ...

 [[165 157 113]
  [165 157 113]
  [165 157 113]
  ..

[[[ 62  45  20]
  [ 64  47  22]
  [ 66  49  24]
  ...
  [174 167 127]
  [174 165 125]
  [175 165 125]]

 [[ 61  44  21]
  [ 59  43  19]
  [ 59  43  19]
  ...
  [175 166 127]
  [174 165 125]
  [174 164 124]]

 [[ 60  45  23]
  [ 59  44  22]
  [ 57  43  21]
  ...
  [174 165 125]
  [173 164 124]
  [172 163 123]]

 ...

 [[135 128  88]
  [135 128  88]
  [135 128  88]
  ...
  [ 81  59  34]
  [ 81  58  32]
  [ 82  58  32]]

 [[135 128  88]
  [135 128  88]
  [135 128  88]
  ...
  [ 81  59  34]
  [ 81  58  32]
  [ 82  58  32]]

 [[135 128  88]
  [135 128  88]
  [135 128  88]
  ...
  [ 81  59  35]
  [ 82  59  34]
  [ 83  59  33]]]
[[[ 62  44  21]
  [ 63  45  22]
  [ 67  47  25]
  ...
  [174 167 127]
  [172 165 125]
  [172 165 125]]

 [[ 61  44  22]
  [ 62  45  23]
  [ 63  44  23]
  ...
  [174 166 127]
  [173 165 125]
  [172 164 124]]

 [[ 60  44  25]
  [ 60  44  25]
  [ 61  44  25]
  ...
  [174 165 125]
  [173 164 124]
  [172 163 123]]

 ...

 [[137 130  88]
  [137 130  88]
  [135 128  88]
  ..

[[[ 66  48  26]
  [ 66  48  26]
  [ 69  51  28]
  ...
  [184 176 139]
  [183 175 138]
  [183 175 138]]

 [[ 65  48  27]
  [ 65  48  27]
  [ 66  49  28]
  ...
  [183 175 138]
  [183 175 138]
  [182 174 136]]

 [[ 67  51  32]
  [ 67  51  32]
  [ 65  51  30]
  ...
  [183 175 138]
  [182 174 136]
  [182 174 136]]

 ...

 [[145 137  98]
  [145 137  98]
  [145 137  98]
  ...
  [101  81  57]
  [103  84  59]
  [103  84  59]]

 [[145 137  98]
  [145 137  98]
  [145 137  98]
  ...
  [ 99  79  54]
  [101  81  57]
  [101  81  57]]

 [[145 137  98]
  [145 137  98]
  [145 137  98]
  ...
  [ 96  76  50]
  [ 98  78  53]
  [ 98  79  55]]]
[[[ 66  47  28]
  [ 68  49  28]
  [ 69  51  29]
  ...
  [184 176 139]
  [183 175 138]
  [183 175 138]]

 [[ 65  47  28]
  [ 65  48  28]
  [ 66  49  28]
  ...
  [183 175 138]
  [183 175 138]
  [182 174 136]]

 [[ 67  51  32]
  [ 67  51  32]
  [ 66  51  32]
  ...
  [183 175 138]
  [182 174 136]
  [182 174 136]]

 ...

 [[144 136  96]
  [144 136  96]
  [144 136  96]
  ..

[[[ 68  50  27]
  [ 70  52  29]
  [ 72  54  32]
  ...
  [186 181 141]
  [186 180 139]
  [186 178 138]]

 [[ 66  50  28]
  [ 68  51  29]
  [ 69  52  30]
  ...
  [185 180 140]
  [185 178 139]
  [186 178 139]]

 [[ 66  51  29]
  [ 65  51  29]
  [ 65  51  29]
  ...
  [186 179 140]
  [185 178 139]
  [185 178 140]]

 ...

 [[143 138  98]
  [143 138  98]
  [143 138  97]
  ...
  [ 36  27  13]
  [ 36  27  14]
  [ 35  25  13]]

 [[143 138  98]
  [143 138  98]
  [143 138  98]
  ...
  [ 36  27  13]
  [ 35  25  13]
  [ 35  25  13]]

 [[143 138  98]
  [143 138  98]
  [143 138  98]
  ...
  [ 36  27  13]
  [ 35  25  13]
  [ 35  25  13]]]
[[[ 70  51  31]
  [ 71  52  32]
  [ 73  55  35]
  ...
  [190 184 144]
  [190 183 143]
  [189 182 142]]

 [[ 66  49  29]
  [ 68  50  30]
  [ 69  51  31]
  ...
  [189 183 143]
  [190 183 143]
  [189 182 142]]

 [[ 66  50  31]
  [ 66  50  31]
  [ 65  50  31]
  ...
  [190 183 143]
  [189 182 142]
  [189 182 142]]

 ...

 [[143 138  98]
  [143 138  98]
  [143 138  98]
  ..

[[[ 63  45  30]
  [ 64  45  29]
  [ 65  45  28]
  ...
  [185 179 141]
  [183 178 140]
  [183 178 140]]

 [[ 65  48  32]
  [ 65  48  32]
  [ 66  48  31]
  ...
  [183 178 140]
  [183 178 140]
  [182 177 139]]

 [[ 65  49  33]
  [ 65  49  33]
  [ 65  49  33]
  ...
  [183 178 140]
  [182 177 139]
  [182 177 139]]

 ...

 [[136 130  92]
  [136 130  92]
  [136 130  92]
  ...
  [253 255 253]
  [253 255 253]
  [253 255 253]]

 [[136 130  92]
  [136 130  92]
  [136 130  92]
  ...
  [253 255 253]
  [253 255 254]
  [253 255 254]]

 [[135 129  91]
  [136 130  92]
  [136 130  92]
  ...
  [253 255 253]
  [253 255 254]
  [253 255 255]]]
[[[ 65  46  28]
  [ 66  47  29]
  [ 67  48  30]
  ...
  [185 179 141]
  [183 178 140]
  [182 177 139]]

 [[ 66  48  31]
  [ 65  47  30]
  [ 65  47  30]
  ...
  [183 178 140]
  [182 177 139]
  [182 177 139]]

 [[ 64  48  32]
  [ 65  48  32]
  [ 66  48  32]
  ...
  [183 178 140]
  [182 177 139]
  [182 177 139]]

 ...

 [[136 130  92]
  [136 130  92]
  [135 129  91]
  ..

[[[ 70  50  25]
  [ 72  52  28]
  [ 74  55  30]
  ...
  [189 184 144]
  [189 184 144]
  [188 183 143]]

 [[ 67  49  25]
  [ 67  49  25]
  [ 68  50  26]
  ...
  [189 184 144]
  [188 183 143]
  [189 183 143]]

 [[ 66  51  29]
  [ 68  52  30]
  [ 68  52  31]
  ...
  [188 183 143]
  [189 183 143]
  [189 182 142]]

 ...

 [[141 136  98]
  [141 136  98]
  [141 136  98]
  ...
  [ 35  25  13]
  [ 34  24  12]
  [ 34  24  12]]

 [[141 137  97]
  [141 137  97]
  [141 137  97]
  ...
  [ 35  25  13]
  [ 35  25  13]
  [ 34  24  12]]

 [[140 136  95]
  [140 136  95]
  [141 137  96]
  ...
  [ 36  26  14]
  [ 35  25  13]
  [ 35  25  13]]]
[[[ 72  51  29]
  [ 73  53  31]
  [ 75  55  33]
  ...
  [191 185 143]
  [191 185 143]
  [191 185 143]]

 [[ 70  50  29]
  [ 70  50  29]
  [ 70  50  29]
  ...
  [191 185 143]
  [191 185 143]
  [190 184 141]]

 [[ 68  50  29]
  [ 68  50  29]
  [ 68  50  29]
  ...
  [191 185 143]
  [190 184 141]
  [190 184 141]]

 ...

 [[144 136  96]
  [144 136  96]
  [144 136  96]
  ..

[[[ 69  51  28]
  [ 70  52  29]
  [ 72  54  32]
  ...
  [192 186 144]
  [192 186 144]
  [191 185 143]]

 [[ 65  48  27]
  [ 65  48  27]
  [ 67  49  28]
  ...
  [192 186 144]
  [192 186 144]
  [191 185 143]]

 [[ 68  52  33]
  [ 67  51  32]
  [ 67  50  30]
  ...
  [192 186 144]
  [191 185 143]
  [191 185 143]]

 ...

 [[145 138  96]
  [145 138  96]
  [145 138  96]
  ...
  [ 42  30  16]
  [ 42  30  16]
  [ 42  30  16]]

 [[145 138  96]
  [145 138  96]
  [145 138  96]
  ...
  [ 42  30  16]
  [ 42  30  16]
  [ 42  30  16]]

 [[145 138  96]
  [145 138  96]
  [145 138  96]
  ...
  [ 42  30  16]
  [ 42  30  16]
  [ 42  30  16]]]
[[[ 72  52  28]
  [ 74  55  30]
  [ 76  57  33]
  ...
  [192 186 144]
  [192 186 144]
  [191 185 143]]

 [[ 68  50  26]
  [ 68  50  26]
  [ 69  51  28]
  ...
  [192 186 144]
  [191 185 143]
  [191 185 143]]

 [[ 67  52  30]
  [ 69  53  32]
  [ 70  53  32]
  ...
  [192 186 144]
  [191 185 143]
  [191 185 143]]

 ...

 [[145 138  96]
  [145 138  96]
  [145 138  96]
  ..

[[[ 70  53  28]
  [ 72  54  29]
  [ 75  56  31]
  ...
  [191 186 141]
  [190 185 140]
  [190 185 140]]

 [[ 69  52  29]
  [ 68  51  27]
  [ 69  51  27]
  ...
  [190 185 140]
  [190 185 140]
  [189 183 139]]

 [[ 67  52  30]
  [ 67  52  30]
  [ 67  52  29]
  ...
  [190 185 140]
  [190 185 140]
  [189 183 139]]

 ...

 [[145 140  97]
  [145 140  97]
  [145 140  97]
  ...
  [ 45  33  14]
  [ 45  33  14]
  [ 46  34  15]]

 [[144 140  97]
  [144 140  97]
  [144 140  97]
  ...
  [ 46  33  16]
  [ 46  34  16]
  [ 46  34  15]]

 [[144 140  97]
  [145 141  98]
  [145 141  98]
  ...
  [ 46  33  17]
  [ 46  34  16]
  [ 46  34  15]]]
[[[ 73  53  29]
  [ 74  55  30]
  [ 76  57  33]
  ...
  [191 186 141]
  [190 185 140]
  [189 183 139]]

 [[ 68  50  26]
  [ 68  50  26]
  [ 68  50  26]
  ...
  [190 185 140]
  [190 185 140]
  [189 183 139]]

 [[ 67  52  31]
  [ 66  51  29]
  [ 67  51  28]
  ...
  [190 185 140]
  [189 183 139]
  [189 183 139]]

 ...

 [[147 141  98]
  [147 141  98]
  [145 140  97]
  ..

[[[ 58  42  22]
  [ 60  43  23]
  [ 63  44  24]
  ...
  [171 165 123]
  [170 164 122]
  [170 164 122]]

 [[ 62  47  27]
  [ 61  46  26]
  [ 61  44  24]
  ...
  [170 164 122]
  [170 164 122]
  [169 163 120]]

 [[ 60  47  28]
  [ 60  47  28]
  [ 60  45  26]
  ...
  [170 164 122]
  [169 163 120]
  [169 163 120]]

 ...

 [[131 123  85]
  [131 123  85]
  [131 123  84]
  ...
  [253 255 254]
  [253 255 254]
  [253 255 254]]

 [[131 123  85]
  [131 123  85]
  [131 123  84]
  ...
  [253 255 254]
  [253 255 254]
  [253 255 254]]

 [[131 123  85]
  [131 123  85]
  [131 123  84]
  ...
  [253 255 254]
  [253 255 254]
  [253 255 254]]]
[[[ 61  42  22]
  [ 62  43  23]
  [ 63  44  24]
  ...
  [171 165 123]
  [171 165 123]
  [170 164 122]]

 [[ 63  45  26]
  [ 63  45  26]
  [ 63  45  26]
  ...
  [171 165 123]
  [170 164 122]
  [170 164 122]]

 [[ 62  46  28]
  [ 62  46  28]
  [ 61  45  26]
  ...
  [170 164 122]
  [170 164 122]
  [170 164 122]]

 ...

 [[130 123  84]
  [130 123  84]
  [131 123  84]
  ..

[[[ 62  48  28]
  [ 61  47  26]
  [ 61  47  26]
  ...
  [171 164 124]
  [171 164 124]
  [170 163 123]]

 [[ 61  48  28]
  [ 60  47  27]
  [ 60  47  27]
  ...
  [171 164 124]
  [171 164 124]
  [170 163 123]]

 [[ 58  47  28]
  [ 58  47  28]
  [ 58  47  28]
  ...
  [171 164 125]
  [170 163 123]
  [170 163 123]]

 ...

 [[129 123  85]
  [129 123  85]
  [130 123  85]
  ...
  [253 255 254]
  [253 255 254]
  [253 255 254]]

 [[129 123  85]
  [129 123  85]
  [131 124  85]
  ...
  [253 255 254]
  [253 255 254]
  [253 255 254]]

 [[129 123  85]
  [129 123  85]
  [131 125  85]
  ...
  [253 255 254]
  [253 255 254]
  [253 255 254]]]
[[[ 61  46  28]
  [ 61  47  28]
  [ 60  46  26]
  ...
  [171 164 124]
  [171 164 124]
  [170 163 123]]

 [[ 60  46  28]
  [ 60  47  28]
  [ 60  47  27]
  ...
  [171 164 124]
  [170 163 123]
  [170 163 123]]

 [[ 58  47  28]
  [ 57  46  27]
  [ 58  46  27]
  ...
  [170 163 123]
  [170 163 123]
  [170 163 123]]

 ...

 [[132 124  86]
  [131 123  85]
  [132 124  86]
  ..

[[[ 64  45  25]
  [ 63  44  24]
  [ 63  43  22]
  ...
  [171 164 124]
  [170 163 123]
  [170 163 123]]

 [[ 64  46  27]
  [ 63  45  25]
  [ 63  44  23]
  ...
  [171 164 124]
  [170 163 123]
  [170 163 123]]

 [[ 63  47  29]
  [ 63  48  29]
  [ 62  47  26]
  ...
  [171 165 123]
  [170 163 123]
  [169 162 122]]

 ...

 [[132 125  85]
  [132 125  85]
  [132 125  85]
  ...
  [253 255 254]
  [253 255 254]
  [253 255 254]]

 [[132 125  85]
  [132 125  85]
  [132 125  85]
  ...
  [253 255 254]
  [253 255 254]
  [253 255 254]]

 [[132 125  85]
  [132 125  85]
  [132 125  85]
  ...
  [253 255 254]
  [253 255 254]
  [253 255 254]]]
[[[ 65  47  25]
  [ 66  47  24]
  [ 68  49  25]
  ...
  [171 164 124]
  [171 165 123]
  [170 164 121]]

 [[ 63  46  24]
  [ 61  44  21]
  [ 62  44  21]
  ...
  [171 164 124]
  [170 164 122]
  [170 164 121]]

 [[ 61  46  25]
  [ 60  45  24]
  [ 60  45  23]
  ...
  [171 164 124]
  [170 164 122]
  [170 164 121]]

 ...

 [[132 125  85]
  [132 125  85]
  [132 125  85]
  ..

[[[ 66  46  22]
  [ 67  48  23]
  [ 70  50  26]
  ...
  [171 165 123]
  [170 164 122]
  [169 163 120]]

 [[ 64  45  22]
  [ 64  45  22]
  [ 66  47  24]
  ...
  [170 164 122]
  [169 163 120]
  [169 163 120]]

 [[ 63  46  25]
  [ 63  46  25]
  [ 63  46  25]
  ...
  [170 164 122]
  [169 163 120]
  [168 162 119]]

 ...

 [[132 124  86]
  [132 124  86]
  [132 124  86]
  ...
  [253 255 254]
  [253 255 254]
  [253 255 254]]

 [[132 124  86]
  [132 124  86]
  [132 124  86]
  ...
  [253 255 254]
  [253 255 254]
  [253 255 254]]

 [[132 124  86]
  [132 124  86]
  [132 124  86]
  ...
  [253 255 254]
  [253 255 254]
  [253 255 254]]]
[[[ 66  46  22]
  [ 70  50  25]
  [ 73  53  29]
  ...
  [171 165 123]
  [170 164 122]
  [169 163 120]]

 [[ 65  46  23]
  [ 66  47  24]
  [ 66  47  24]
  ...
  [170 164 122]
  [169 163 120]
  [170 163 120]]

 [[ 63  46  25]
  [ 63  46  25]
  [ 63  46  25]
  ...
  [171 164 122]
  [170 162 120]
  [171 162 120]]

 ...

 [[132 124  86]
  [132 124  86]
  [132 124  86]
  ..

[[[140 130  92]
  [140 131  93]
  [141 133  95]
  ...
  [156 149 109]
  [156 149 109]
  [155 148 108]]

 [[111  99  64]
  [115 104  69]
  [123 113  77]
  ...
  [156 149 109]
  [155 148 108]
  [155 148 108]]

 [[ 72  57  27]
  [ 78  64  33]
  [ 85  71  40]
  ...
  [155 148 108]
  [155 148 108]
  [154 147 107]]

 ...

 [[119 114  76]
  [119 114  76]
  [119 114  76]
  ...
  [253 255 254]
  [253 255 254]
  [253 255 254]]

 [[118 113  75]
  [118 113  75]
  [118 113  75]
  ...
  [253 255 254]
  [253 255 254]
  [253 255 254]]

 [[118 113  75]
  [118 113  75]
  [118 113  75]
  ...
  [253 255 254]
  [253 255 254]
  [253 255 254]]]
[[[ 68  51  24]
  [ 71  55  27]
  [ 79  64  34]
  ...
  [156 149 109]
  [156 149 109]
  [156 149 109]]

 [[ 59  43  19]
  [ 61  45  20]
  [ 62  46  20]
  ...
  [156 149 109]
  [155 148 108]
  [155 148 108]]

 [[ 53  37  19]
  [ 54  38  19]
  [ 55  39  18]
  ...
  [155 148 108]
  [155 148 108]
  [154 147 107]]

 ...

 [[121 113  76]
  [121 114  76]
  [120 114  76]
  ..

[[[ 76  56  27]
  [ 76  56  27]
  [ 79  58  29]
  ...
  [164 157 117]
  [163 156 116]
  [162 155 115]]

 [[ 66  46  19]
  [ 67  47  20]
  [ 68  48  21]
  ...
  [163 156 116]
  [163 156 116]
  [162 155 115]]

 [[ 61  42  20]
  [ 61  42  20]
  [ 63  44  20]
  ...
  [163 156 116]
  [162 155 115]
  [162 155 115]]

 ...

 [[127 120  80]
  [128 121  81]
  [128 121  81]
  ...
  [253 255 254]
  [253 255 254]
  [253 255 254]]

 [[127 120  80]
  [128 121  81]
  [128 121  81]
  ...
  [253 255 254]
  [253 255 254]
  [253 255 254]]

 [[127 120  80]
  [127 120  80]
  [128 121  81]
  ...
  [253 255 254]
  [253 255 254]
  [253 255 254]]]
[[[ 73  53  22]
  [ 74  55  22]
  [ 82  63  30]
  ...
  [164 157 117]
  [163 156 116]
  [162 155 115]]

 [[ 65  46  17]
  [ 66  47  17]
  [ 67  49  17]
  ...
  [163 156 116]
  [163 156 116]
  [162 155 115]]

 [[ 60  42  18]
  [ 60  42  17]
  [ 59  42  15]
  ...
  [163 156 116]
  [162 155 115]
  [162 155 115]]

 ...

 [[125 120  82]
  [125 120  82]
  [125 120  82]
  ..